kind: Service
apiVersion: v1
metadata:
  name: app-security-service
spec:
  type: ClusterIP
  selector:
    app: app-security-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
    name: http
