resources:
  - ../../base

commonLabels:
  environment: dev

namePrefix: dev-

configMapGenerator:
  - name: app-security-configmap
    behavior: merge
    files:
      - .env=config.properties
    env: env