apiVersion: v1
kind: ConfigMap
metadata:
  name: app-security-configmap
data:
  NACOS_SERVERADDR: 67.205.143.150:8848
  NACOS_NAMESPACE: aforo255
  NACOS_IDENTITYKEY: nacos
  NACOS_IDENTITYVALUE: nacos
  NACOS_ENV: PROD