name: Release Docker Image

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
  DOCKER_IMAGE_NAME: aforo255-micro-security

jobs:
  docker:
    name: CI Release
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run:  echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username $DOCKER_HUB_USER --password-stdin

    - name: Build the Docker image
      run: docker build --tag $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME:$GITHUB_RUN_NUMBER --tag $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME:latest .

    - name: Push the docker image
      run: docker push --all-tags $DOCKER_HUB_USER/$DOCKER_IMAGE_NAME

  merge-branch:
    name: Merge to main
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN  }}